# .goreleaser.yml
# Build customization
builds:
  - main: cmd/gosvm/main.go
    binary: gosvm
    goos:
      #- windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64
checksum:
    name_template: '{{ .ProjectName }}_checksums.txt'

archive:
  name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  replacements:
    darwin: Darwin
    linux: Linux
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
