[[constraint]]
  name = "github.com/pelletier/go-toml"
  version = "1.1.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.1.1"

[[constraint]]
  name = "github.com/golang/dep"
  version = "0.4.1"
